name: The Barbers
favicon: null
layout_spectrum: 0.012276618042960763
typography_spectrum: 0.239806798286736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45079484628513455
  lightness: 0.8169744373299181
  saturation: 0.10799629660323262
  rhythmicContrast: 0.22045920439995825
purpose: []
